python: can't open file 'manager.py': [Errno 2] No such file or directory
python: can't open file 'manager.py': [Errno 2] No such file or directory
python: can't open file 'manager.py': [Errno 2] No such file or directory
python: can't open file 'manager.py': [Errno 2] No such file or directory
python: can't open file 'manager.py': [Errno 2] No such file or directory
python: can't open file 'manager.py': [Errno 2] No such file or directory
[22/May/2018 22:15:09] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:17] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:19] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:19] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:20] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:20] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:20] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:20] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:21] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:21] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:21] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:15:23] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:17:45] "GET / HTTP/1.0" 200 8061
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.906 seconds.
Prefix dict has been built succesfully.
[22/May/2018 22:19:03] "GET /post/1/ HTTP/1.0" 200 11106
[22/May/2018 22:19:08] "GET /admin/ HTTP/1.0" 200 7216
[22/May/2018 22:19:12] "GET /admin/blog/post/ HTTP/1.0" 200 5516
[22/May/2018 22:19:12] "GET /admin/jsi18n/ HTTP/1.0" 200 7684
[22/May/2018 22:19:14] "GET /admin/blog/post/add/ HTTP/1.0" 200 10476
[22/May/2018 22:19:14] "GET /admin/jsi18n/ HTTP/1.0" 200 7684
[22/May/2018 22:35:50] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:36:22] "GET /?nsukey=B1g1ETY2jMSdxDUnZ2BXf2B0OPqoPr2FNT4TY5f6urGiT2FjwMBkIDMZu7MKLeIZUDfhGPzk71rZ5GP6CgsxFfpLnAQS13xYtaC2B4pGGA2kWfeu1B2F7EsJlmpv2pazhqYDOCUYNyfSpodCEXfiG70hEFe8nvkGAEMkXF3bRS9BsCGXo3D HTTP/1.0" 200 8061
[22/May/2018 22:36:22] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:36:22] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:36:33] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:36:41] "GET /post/1/ HTTP/1.0" 200 11106
[22/May/2018 22:36:42] "GET /post/1 HTTP/1.0" 301 0
[22/May/2018 22:36:42] "GET /post/1/ HTTP/1.0" 200 11106
[22/May/2018 22:36:51] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:36:51] "GET / HTTP/1.0" 200 8061
[22/May/2018 22:37:41] "GET /post/1 HTTP/1.0" 301 0
Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/http/request.py", line 105, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '39.104.1.195'. You may need to add '39.104.1.195' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 74, in response_for_exception
    extra={'status_code': 400, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
[23/May/2018 00:26:12] "GET / HTTP/1.0" 500 59
[23/May/2018 00:52:59] "GET / HTTP/1.0" 200 8061
[23/May/2018 00:56:33] "GET / HTTP/1.0" 200 8061
[23/May/2018 00:57:28] "GET / HTTP/1.0" 200 8061
[23/May/2018 02:54:59] "GET / HTTP/1.0" 200 8061
[23/May/2018 03:09:05] "GET / HTTP/1.0" 200 8061
[23/May/2018 04:11:52] "GET / HTTP/1.0" 200 8061
[23/May/2018 05:35:21] "GET / HTTP/1.0" 200 8061
Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/http/request.py", line 105, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 74, in response_for_exception
    extra={'status_code': 400, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
[23/May/2018 07:12:19] "GET /cache/global/img/gs.gif HTTP/1.0" 500 59
[23/May/2018 07:13:26] "GET / HTTP/1.0" 200 8061
Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/http/request.py", line 105, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 74, in response_for_exception
    extra={'status_code': 400, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
[23/May/2018 07:52:41] "GET /cache/global/img/gs.gif HTTP/1.0" 500 59
[23/May/2018 07:56:34] "GET / HTTP/1.0" 200 8061
[23/May/2018 08:08:32] "GET /?nsukey=ggWTzS74X7gzhfWQkmkrtnJpTdcZOh8CeLBlPrWgEfnq2FRndDPHsHinTbaMcZXM2utlyyXbs2S3vcD2BCtYcz2B9XynoRVb6l8xMCYa2FwmxQeWGyMS7ifsYBPo2q7sWWamuyo8ObELnogLMXIkP3pQUcbSZ2FmetdDqOogPePjJlTosJF6MN6DVEEjkG8NhGO2FDW5qbRZgC4eI1d2d3y9dpyg3D3D HTTP/1.0" 200 8061
[23/May/2018 08:08:32] "GET / HTTP/1.0" 200 8061
[23/May/2018 08:08:32] "GET / HTTP/1.0" 200 8061
[23/May/2018 08:09:32] "GET /?nsukey=ggWTzS74X7gzhfWQkmkrtnJpTdcZOh8CeLBlPrWgEfnq%2FRndDPHsHinTbaMcZXM2utlyyXbs2S3vcD%2BCtYcz%2B9XynoRVb6l8xMCYa%2FwmxQeWGyMS7ifsYBPo2q7sWWamuyo8ObELnogLMXIkP3pQUcbSZ%2FmetdDqOogPePjJlTosJF6MN6DVEEjkG8NhGO%2FDW5qbRZgC4eI1d2d3y9dpyg%3D%3D HTTP/1.0" 200 8061
[23/May/2018 09:14:48] "GET /?nsukey=gkX7HnsDiohYMO2z2FkqDJEl8HnZ8gnOEKeBARM0zPxhdIcLGhhrHT1WdulqILxfXlx7u6pMqHkSAgh2PgluYDwnOpTcsVQnf8HAvNydehSmcmp2BkZrBS7yuW1NHGT8lF5T1gQ7ntOk7HexhTSXK8o70F0LLz2Bz6DHAGSlMKWofLf2Fo1xNT4sV9HibkRXc15LU7LYiVV9EOSLo92FQGwfflA3D3D HTTP/1.0" 200 8061
[23/May/2018 09:14:48] "GET / HTTP/1.0" 200 8061
[23/May/2018 09:14:49] "GET / HTTP/1.0" 200 8061
[23/May/2018 09:15:48] "GET /?nsukey=gkX7HnsDiohYMO2z%2FkqDJEl8HnZ8gnOEKeBARM0zPxhdIcLGhhrHT1WdulqILxfXlx7u6pMqHkSAgh2PgluYDwnOpTcsVQnf8HAvNydehSmcmp%2BkZrBS7yuW1NHGT8lF5T1gQ7ntOk7HexhTSXK8o70F0LLz%2Bz6DHAGSlMKWofLf%2Fo1xNT4sV9HibkRXc15LU7LYiVV9EOSLo9%2FQGwfflA%3D%3D HTTP/1.0" 200 8061
Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/http/request.py", line 105, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '39.104.9.201'. You may need to add '39.104.9.201' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 74, in response_for_exception
    extra={'status_code': 400, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
[23/May/2018 09:15:56] "GET / HTTP/1.0" 500 59
[23/May/2018 09:17:32] "GET /?nsukey=fA2Oi6VfjUE4P5tPBD3HELoNHhsVU1WSCQFyIdeUVwWNLZrZrObeNBQ1eToRMGVnHCs2Bb8N43t0M8NMeYITYWYDHjPY2Fya2FLuyq5Ty1lAuyZk5z4bHRnF1QK82Kmabte7e2FG5V2B8SFT5c2m7BkGvUvcLlHR86FsgExIGI1vSxA4qSLvKnr8D9E22BPZYu2BF8ZuoV8qH52FyMSOAs3qhqtqDw3D3D HTTP/1.0" 200 8061
[23/May/2018 09:18:32] "GET /?nsukey=fA2Oi6VfjUE4P5tPBD3HELoNHhsVU1WSCQFyIdeUVwWNLZrZrObeNBQ1eToRMGVnHCs%2Bb8N43t0M8NMeYITYWYDHjPY%2Fya%2FLuyq5Ty1lAuyZk5z4bHRnF1QK82Kmabte7e%2FG5V%2B8SFT5c2m7BkGvUvcLlHR86FsgExIGI1vSxA4qSLvKnr8D9E2%2BPZYu%2BF8ZuoV8qH5%2FyMSOAs3qhqtqDw%3D%3D HTTP/1.0" 200 8061
[23/May/2018 09:20:15] "GET / HTTP/1.0" 200 8061
Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/http/request.py", line 105, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '112.124.42.80'. You may need to add '112.124.42.80' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 74, in response_for_exception
    extra={'status_code': 400, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
    response = self.get_response(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 118, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 119, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 122, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/log.py", line 125, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/sites/demo.wyq.top/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sites/demo.wyq.top/env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 4, in <module>
    import ssl
  File "/usr/local/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
[23/May/2018 09:45:12] "HEAD / HTTP/1.0" 500 59
[23/May/2018 09:48:51] "GET / HTTP/1.0" 200 8061
[23/May/2018 09:48:58] "GET /post/1/ HTTP/1.0" 200 11106
[23/May/2018 09:49:00] "GET / HTTP/1.0" 200 8061
[23/May/2018 09:49:07] "GET /search/?q=%E5%8D%9A%E5%AE%A2 HTTP/1.0" 200 8029
[23/May/2018 09:57:35] "GET / HTTP/1.0" 200 8061
[23/May/2018 10:20:58] "GET /search/?q=%E5%8D%9A%E5%AE%A2 HTTP/1.0" 200 8029
[23/May/2018 17:19:48] "GET / HTTP/1.0" 200 8061
[23/May/2018 17:25:30] "GET / HTTP/1.0" 200 8061
[23/May/2018 17:25:33] "GET / HTTP/1.0" 200 8061
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.902 seconds.
Prefix dict has been built succesfully.
[23/May/2018 17:25:36] "GET /post/1/ HTTP/1.0" 200 11553
[23/May/2018 17:28:05] "GET / HTTP/1.0" 200 8061
[23/May/2018 17:28:25] "GET / HTTP/1.0" 200 8061
[23/May/2018 17:29:36] "GET / HTTP/1.0" 200 8061
[23/May/2018 17:30:14] "GET / HTTP/1.0" 200 8061
[23/May/2018 18:45:10] "GET / HTTP/1.0" 200 8061
[23/May/2018 18:45:42] "GET / HTTP/1.0" 200 8061
[23/May/2018 19:03:52] "GET /echo.php?info=1234567890 HTTP/1.0" 400 26
[23/May/2018 19:20:14] "GET /nginx-logo.png HTTP/1.0" 404 88
[23/May/2018 19:25:14] "GET / HTTP/1.0" 200 8061
[23/May/2018 20:05:03] "GET / HTTP/1.0" 400 26
[23/May/2018 20:23:27] "GET / HTTP/1.0" 200 8061
[23/May/2018 20:36:53] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:29:35] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:29:38] "GET /favicon.ico HTTP/1.0" 404 85
[23/May/2018 21:29:45] "GET /post/1/ HTTP/1.0" 200 11553
[23/May/2018 21:29:50] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:30:03] "GET /search/?q=%E5%8D%9A%E5%AE%A2 HTTP/1.0" 200 8029
[23/May/2018 21:30:06] "GET /post/1/ HTTP/1.0" 200 11553
[23/May/2018 21:30:09] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:32:21] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:38:02] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:38:54] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:55:00] "GET / HTTP/1.0" 200 8061
[23/May/2018 21:56:09] "HEAD /htdocs.zip HTTP/1.0" 404 84
[23/May/2018 22:04:20] "GET / HTTP/1.0" 200 8061
[23/May/2018 22:07:01] "HEAD /htdocs.rar HTTP/1.0" 404 84
[23/May/2018 22:11:46] "GET /comment/post/1/ HTTP/1.0" 302 0
[23/May/2018 22:11:46] "GET /post/1/ HTTP/1.0" 200 11553
[23/May/2018 22:31:19] "GET / HTTP/1.0" 200 8061
[24/May/2018 00:26:54] "GET / HTTP/1.0" 400 26
[24/May/2018 00:49:26] "GET / HTTP/1.0" 200 8061
[24/May/2018 01:20:57] "GET / HTTP/1.0" 200 8061
[24/May/2018 01:38:40] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[24/May/2018 02:07:58] "GET / HTTP/1.0" 200 8061
[24/May/2018 02:30:25] "GET / HTTP/1.0" 200 8061
[24/May/2018 03:10:53] "GET / HTTP/1.0" 200 8061
[24/May/2018 03:27:56] "GET / HTTP/1.0" 200 8061
[24/May/2018 03:33:15] "GET / HTTP/1.0" 200 8061
[24/May/2018 03:55:04] "GET / HTTP/1.0" 200 8061
[24/May/2018 04:11:20] "GET / HTTP/1.0" 200 8061
[24/May/2018 04:31:15] "GET / HTTP/1.0" 200 8061
[24/May/2018 05:31:26] "GET / HTTP/1.0" 200 8061
[24/May/2018 05:50:01] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[24/May/2018 06:15:44] "GET / HTTP/1.0" 200 8061
[24/May/2018 06:33:31] "GET / HTTP/1.0" 200 8061
[24/May/2018 06:41:17] "GET / HTTP/1.0" 200 8061
[24/May/2018 06:41:17] "GET / HTTP/1.0" 200 8061
[24/May/2018 07:00:12] "GET / HTTP/1.0" 200 8061
[24/May/2018 07:42:52] "GET / HTTP/1.0" 200 8061
[24/May/2018 08:02:40] "GET /tools/phpMyAdmin/index.php HTTP/1.0" 404 100
[24/May/2018 08:02:40] "GET /phpmyadmin-old/index.php HTTP/1.0" 404 98
[24/May/2018 08:02:40] "GET /phpMyAdminold/index.php HTTP/1.0" 404 97
[24/May/2018 08:02:40] "GET /phpMyAdmin.old/index.php HTTP/1.0" 404 98
[24/May/2018 08:02:40] "GET /pma-old/index.php HTTP/1.0" 404 91
[24/May/2018 08:02:40] "GET /claroline/phpMyAdmin/index.php HTTP/1.0" 404 104
[24/May/2018 08:02:40] "GET /typo3/phpmyadmin/index.php HTTP/1.0" 404 100
[24/May/2018 08:02:40] "GET /phpma/index.php HTTP/1.0" 404 89
[24/May/2018 08:02:40] "GET /phpmyadmin/phpmyadmin/index.php HTTP/1.0" 404 105
[24/May/2018 08:02:40] "GET /phpMyAdmin/phpMyAdmin/index.php HTTP/1.0" 404 105
[24/May/2018 08:25:28] "GET / HTTP/1.0" 400 26
[24/May/2018 08:35:17] "GET / HTTP/1.0" 200 8061
[24/May/2018 08:35:18] "GET /favicon.ico HTTP/1.0" 404 85
[24/May/2018 08:35:25] "GET /post/1/ HTTP/1.0" 200 11553
[24/May/2018 08:36:11] "GET / HTTP/1.0" 200 8061
[24/May/2018 08:51:27] "GET / HTTP/1.0" 200 8061
[24/May/2018 08:51:29] "GET / HTTP/1.0" 200 8061
[24/May/2018 08:51:32] "GET /category/4/ HTTP/1.0" 200 8061
[24/May/2018 08:51:34] "GET /archives/2018/5/ HTTP/1.0" 200 8061
[24/May/2018 08:51:35] "GET /post/1/ HTTP/1.0" 200 11553
[24/May/2018 08:51:38] "GET / HTTP/1.0" 200 8061
[24/May/2018 08:51:49] "GET /tag/6/ HTTP/1.0" 200 8061
[24/May/2018 09:47:23] "GET / HTTP/1.0" 200 8061
[24/May/2018 10:46:30] "GET / HTTP/1.0" 200 8061
[24/May/2018 10:50:20] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
Performing system checks...

System check identified no issues (0 silenced).
May 23, 2018 - 17:25:28
Django version 2.0.5, using settings 'myblog.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
May 24, 2018 - 10:55:47
Django version 2.0.5, using settings 'myblog.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/May/2018 11:03:26] "GET / HTTP/1.0" 400 26
Performing system checks...

System check identified no issues (0 silenced).
May 24, 2018 - 10:58:29
Django version 2.0.5, using settings 'myblog.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/May/2018 11:14:23] "GET / HTTP/1.0" 400 26
[24/May/2018 11:16:50] "GET / HTTP/1.0" 400 26
[24/May/2018 11:17:20] "GET / HTTP/1.0" 400 26
Performing system checks...

System check identified no issues (0 silenced).
May 24, 2018 - 11:11:58
Django version 2.0.5, using settings 'myblog.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/May/2018 17:34:14] "GET / HTTP/1.0" 200 8061
[24/May/2018 17:34:27] "GET / HTTP/1.0" 200 8061
[24/May/2018 17:34:29] "GET / HTTP/1.0" 200 8061
[24/May/2018 17:34:39] "GET /robot/ HTTP/1.0" 404 80
[24/May/2018 17:34:48] "GET /?signature=f9686193a296397d4e88f4e4a18b483d655a86da&echostr=6607124520771172157&timestamp=1527154488&nonce=631462744 HTTP/1.0" 200 8061
[24/May/2018 19:15:13] "GET / HTTP/1.0" 200 8061
[24/May/2018 19:15:15] "GET /favicon.ico HTTP/1.0" 404 85
[24/May/2018 19:15:35] "GET /?signature=4b926ccb2b6fbf2a9c9f51c596ccfc0f17092c05&echostr=8817982627357122551&timestamp=1527160535&nonce=4242817776 HTTP/1.0" 200 8061
[24/May/2018 19:16:03] "GET /?signature=27f74cdd3ddebc9d844ee4095963483a710c6402&echostr=6283230789724258295&timestamp=1527160563&nonce=293551681 HTTP/1.0" 200 8061
[24/May/2018 19:25:58] "GET /BGCC/Tpl/Public/css/login.css HTTP/1.0" 404 103
[24/May/2018 19:38:31] "GET / HTTP/1.0" 200 8061
[24/May/2018 20:00:25] "GET / HTTP/1.0" 200 8061
[24/May/2018 20:02:28] "GET / HTTP/1.0" 200 8061
[24/May/2018 20:02:30] "GET / HTTP/1.0" 200 8061
Performing system checks...

System check identified no issues (0 silenced).
May 24, 2018 - 17:34:12
Django version 2.0.5, using settings 'myblog.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[25/May/2018 10:40:43] "GET / HTTP/1.0" 200 8061
[25/May/2018 10:52:03] "POST /weixin?signature=264b62a3406d41292953e41e6213cc54ad368ea1&timestamp=1527216723&nonce=1116516105&openid=oQZgM1I2F-A4hEgqWU6ipHn5mBHU HTTP/1.0" 500 27
[25/May/2018 10:58:22] "POST /weixin?signature=f1a2d4b461cd8dec979b4918e426a63f73099fc0&timestamp=1527217102&nonce=2091444699&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 328
[25/May/2018 10:58:27] "POST /weixin?signature=f825f9517154530d7257092a173caa612634dcff&timestamp=1527217107&nonce=1847652368&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 500 27
[25/May/2018 10:58:41] "GET / HTTP/1.0" 200 8061
[25/May/2018 10:58:44] "GET / HTTP/1.0" 200 8061
[25/May/2018 10:58:56] "POST /weixin?signature=ba70a56dc7160bfff9f17d0526568008ac325401&timestamp=1527217136&nonce=1659189355&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 438
[25/May/2018 10:59:09] "POST /weixin?signature=e455bf9ad7024758742df042f7c29d6c0b99b541&timestamp=1527217149&nonce=1651390423&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 500 27
[27/May/2018 09:18:16] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:19:14] "POST /weixin?signature=e4246169ecb241edbcf11567a73239bf83c7bfda&timestamp=1527383954&nonce=375599267&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 438
[27/May/2018 09:19:28] "POST /weixin?signature=cdbf2d1924e6b703271ac5861adce85990d20554&timestamp=1527383968&nonce=45007654&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 500 27
[27/May/2018 09:19:31] "POST /weixin?signature=a4204df32118814a2c1b2f936e6ad37268d4ec27&timestamp=1527383971&nonce=2101106172&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 898
[27/May/2018 09:20:24] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:20:24] "GET /favicon.ico HTTP/1.0" 404 85
[27/May/2018 09:20:29] "GET /favicon.ico HTTP/1.0" 404 85
[27/May/2018 09:20:31] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:20:31] "GET /favicon.ico HTTP/1.0" 404 85
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 1.146 seconds.
Prefix dict has been built succesfully.
[27/May/2018 09:20:34] "GET /post/1/ HTTP/1.0" 200 11553
[27/May/2018 09:20:35] "GET /favicon.ico HTTP/1.0" 404 85
[27/May/2018 09:20:56] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:21:03] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:21:12] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:21:21] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:26:06] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:26:06] "GET /favicon.ico HTTP/1.0" 404 85
[27/May/2018 09:26:09] "GET /post/1/ HTTP/1.0" 200 11553
[27/May/2018 09:26:09] "GET /favicon.ico HTTP/1.0" 404 85
[27/May/2018 09:26:13] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:26:13] "GET /favicon.ico HTTP/1.0" 404 85
[27/May/2018 09:26:27] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:26:30] "GET / HTTP/1.0" 200 8061
[27/May/2018 09:26:51] "GET /post/1/ HTTP/1.0" 200 11553
[27/May/2018 09:27:11] "GET /post/1/ HTTP/1.0" 200 11553
[27/May/2018 10:33:58] "GET / HTTP/1.0" 200 8061
[27/May/2018 11:47:51] "GET / HTTP/1.0" 200 8061
[27/May/2018 12:50:15] "GET / HTTP/1.0" 200 8061
[27/May/2018 13:36:54] "GET / HTTP/1.0" 200 8061
[27/May/2018 13:36:54] "HEAD / HTTP/1.0" 400 26
[27/May/2018 13:44:24] "GET / HTTP/1.0" 200 8061
[27/May/2018 15:52:44] "GET / HTTP/1.0" 200 8061
[27/May/2018 16:12:05] "GET / HTTP/1.0" 400 26
[27/May/2018 16:17:04] "GET / HTTP/1.0" 200 8061
[27/May/2018 17:15:22] "GET / HTTP/1.0" 200 8061
[27/May/2018 18:14:22] "GET / HTTP/1.0" 200 8061
[27/May/2018 18:14:47] "GET / HTTP/1.0" 200 8061
[27/May/2018 18:57:13] "GET / HTTP/1.0" 200 8061
[27/May/2018 18:58:11] "GET / HTTP/1.0" 200 8061
[27/May/2018 19:00:39] "GET /echo.php?info=1234567890 HTTP/1.0" 400 26
[27/May/2018 19:54:37] "GET / HTTP/1.0" 200 8061
[27/May/2018 20:10:20] "GET / HTTP/1.0" 200 8061
[27/May/2018 20:45:46] "GET / HTTP/1.0" 200 8061
[27/May/2018 21:08:18] "GET / HTTP/1.0" 200 8061
[27/May/2018 21:50:47] "GET / HTTP/1.0" 200 8061
[27/May/2018 21:56:13] "GET / HTTP/1.0" 200 8061
[27/May/2018 21:56:13] "GET / HTTP/1.0" 200 8061
[27/May/2018 22:40:48] "GET / HTTP/1.0" 200 8061
[27/May/2018 22:53:41] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[27/May/2018 23:07:56] "GET / HTTP/1.0" 200 8061
[28/May/2018 00:04:27] "GET / HTTP/1.0" 200 8061
[28/May/2018 00:17:59] "GET / HTTP/1.0" 400 26
[28/May/2018 00:48:43] "GET / HTTP/1.0" 200 8061
[28/May/2018 01:29:36] "GET / HTTP/1.0" 200 8061
[28/May/2018 02:10:13] "GET / HTTP/1.0" 200 8061
[28/May/2018 02:10:13] "GET / HTTP/1.0" 200 8061
[28/May/2018 02:35:56] "GET / HTTP/1.0" 200 8061
[28/May/2018 02:42:11] "GET / HTTP/1.0" 200 8061
[28/May/2018 03:00:11] "GET / HTTP/1.0" 200 8061
[28/May/2018 03:53:33] "GET / HTTP/1.0" 400 26
[28/May/2018 04:37:20] "GET / HTTP/1.0" 200 8061
[28/May/2018 04:49:34] "GET / HTTP/1.0" 200 8061
[28/May/2018 04:52:32] "GET / HTTP/1.0" 200 8061
[28/May/2018 05:12:22] "GET / HTTP/1.0" 200 8061
[28/May/2018 05:26:45] "GET / HTTP/1.0" 200 8061
[28/May/2018 05:52:57] "GET / HTTP/1.0" 200 8061
[28/May/2018 08:09:33] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[28/May/2018 09:28:35] "GET / HTTP/1.0" 200 8061
[28/May/2018 09:28:35] "GET / HTTP/1.0" 200 8061
[28/May/2018 10:04:44] "GET /user/soapCaller.bs HTTP/1.0" 404 92
[28/May/2018 10:47:45] "GET / HTTP/1.0" 200 8061
[28/May/2018 11:57:39] "HEAD / HTTP/1.0" 200 8061
[28/May/2018 11:57:40] "GET / HTTP/1.0" 200 8061
[28/May/2018 12:05:40] "GET / HTTP/1.0" 200 8061
[28/May/2018 12:15:18] "GET / HTTP/1.0" 200 8061
[28/May/2018 12:26:49] "GET / HTTP/1.0" 200 8061
[28/May/2018 13:04:46] "GET /xmlrpc.php HTTP/1.0" 404 84
[28/May/2018 14:03:00] "GET / HTTP/1.0" 200 8061
[28/May/2018 14:26:06] "GET / HTTP/1.0" 200 8061
[28/May/2018 15:49:35] "GET / HTTP/1.0" 200 8061
[28/May/2018 16:23:36] "GET /muieblackcat HTTP/1.0" 404 86
[28/May/2018 16:23:36] "GET /phpMyAdmin/scripts/setup.php HTTP/1.0" 404 102
[28/May/2018 16:23:36] "GET /phpmyadmin/scripts/setup.php HTTP/1.0" 404 102
[28/May/2018 16:23:36] "GET /pma/scripts/setup.php HTTP/1.0" 404 95
[28/May/2018 16:23:36] "GET /myadmin/scripts/setup.php HTTP/1.0" 404 99
[28/May/2018 16:23:36] "GET /MyAdmin/scripts/setup.php HTTP/1.0" 404 99
[28/May/2018 16:23:37] "GET /scripts/setup.php HTTP/1.0" 404 91
[28/May/2018 16:23:37] "GET /admin/scripts/setup.php HTTP/1.0" 404 97
[28/May/2018 16:23:37] "GET /admin/pma/scripts/setup.php HTTP/1.0" 404 101
[28/May/2018 16:23:37] "GET /admin/phpmyadmin/scripts/setup.php HTTP/1.0" 404 108
[28/May/2018 16:23:37] "GET /db/scripts/setup.php HTTP/1.0" 404 94
[28/May/2018 16:23:37] "GET /dbadmin/scripts/setup.php HTTP/1.0" 404 99
[28/May/2018 16:23:38] "GET /myadmin/scripts/setup.php HTTP/1.0" 404 99
[28/May/2018 16:23:38] "GET /mysql/scripts/setup.php HTTP/1.0" 404 97
[28/May/2018 16:23:38] "GET /mysqladmin/scripts/setup.php HTTP/1.0" 404 102
[28/May/2018 16:23:38] "GET /typo3/phpmyadmin/scripts/setup.php HTTP/1.0" 404 108
[28/May/2018 16:23:38] "GET /phpadmin/scripts/setup.php HTTP/1.0" 404 100
[28/May/2018 16:23:38] "GET /pma/scripts/setup.php HTTP/1.0" 404 95
[28/May/2018 16:23:38] "GET /web/phpMyAdmin/scripts/setup.php HTTP/1.0" 404 106
[28/May/2018 16:23:39] "GET /xampp/phpmyadmin/scripts/setup.php HTTP/1.0" 404 108
[28/May/2018 16:23:39] "GET /web/scripts/setup.php HTTP/1.0" 404 95
[28/May/2018 16:23:39] "GET /php-my-admin/scripts/setup.php HTTP/1.0" 404 104
[28/May/2018 16:23:39] "GET /websql/scripts/setup.php HTTP/1.0" 404 98
[28/May/2018 16:23:39] "GET /phpMyAdmin-2/scripts/setup.php HTTP/1.0" 404 104
[28/May/2018 16:23:39] "GET /_phpmyadmin/scripts/setup.php HTTP/1.0" 404 103
[28/May/2018 16:23:40] "GET /administrator/components/com_joommyadmin/phpmyadmin/scripts/setup.php HTTP/1.0" 404 143
[28/May/2018 16:23:40] "GET /apache-default/phpmyadmin/scripts/setup.php HTTP/1.0" 404 117
[28/May/2018 16:23:40] "GET /blog/phpmyadmin/scripts/setup.php HTTP/1.0" 404 107
[28/May/2018 16:23:40] "GET /cpanelphpmyadmin/scripts/setup.php HTTP/1.0" 404 108
[28/May/2018 16:23:40] "GET /cpphpmyadmin/scripts/setup.php HTTP/1.0" 404 104
[28/May/2018 16:23:40] "GET /forum/phpmyadmin/scripts/setup.php HTTP/1.0" 404 108
[28/May/2018 16:23:41] "GET /php/phpmyadmin/scripts/setup.php HTTP/1.0" 404 106
[28/May/2018 16:23:41] "GET /phpmyadmin/scripts/setup.php HTTP/1.0" 404 102
[28/May/2018 16:23:41] "GET /phpMyAdmin-2.10.0.0/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:41] "GET /phpMyAdmin-2.10.0.1/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:41] "GET /phpMyAdmin-2.10.0.2/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:41] "GET /phpMyAdmin-2.10.0/scripts/setup.php HTTP/1.0" 404 109
[28/May/2018 16:23:41] "GET /phpMyAdmin-2.10.1.0/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:42] "GET /phpMyAdmin-2.10.2.0/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:42] "GET /phpMyAdmin-2.11.0.0/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:42] "GET /phpMyAdmin-2.11.1-all-languages/scripts/setup.php HTTP/1.0" 404 123
[28/May/2018 16:23:42] "GET /phpMyAdmin-2.11.1.0/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:42] "GET /phpMyAdmin-2.11.1.1/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:42] "GET /phpMyAdmin-2.11.1.2/scripts/setup.php HTTP/1.0" 404 111
[28/May/2018 16:23:43] "GET /phpMyAdmin-2.6.1-pl2/scripts/setup.php HTTP/1.0" 404 112
[28/May/2018 16:23:43] "GET /phpMyAdmin-2.6.1-pl3/scripts/setup.php HTTP/1.0" 404 112
[28/May/2018 16:24:08] "GET /phpMyAdmin-2.7.0-pl2/scripts/setup.php HTTP/1.0" 404 112
[28/May/2018 16:24:51] "GET /phpMyAdmin-2.9.0.1/scripts/setup.php HTTP/1.0" 404 110
[28/May/2018 16:24:53] "GET / HTTP/1.0" 400 26
[28/May/2018 16:24:55] "GET /phpMyAdmin-2.9.0/scripts/setup.php HTTP/1.0" 404 108
[28/May/2018 16:25:10] "GET /phpMyAdmin-3.0.1.0-english/scripts/setup.php HTTP/1.0" 404 118
[28/May/2018 16:25:18] "GET /phpMyAdmin-3.1.0.0-english/scripts/setup.php HTTP/1.0" 404 118
[28/May/2018 16:25:21] "GET /phpMyAdmin-3.1.1.0-all-languages/scripts/setup.php HTTP/1.0" 404 124
[28/May/2018 16:25:21] "GET /phpMyAdmin-3.1.2.0-all-languages/scripts/setup.php HTTP/1.0" 404 124
[28/May/2018 16:25:21] "GET /phpMyAdmin-3.1.2.0-english/scripts/setup.php HTTP/1.0" 404 118
[28/May/2018 16:25:21] "GET /phpMyAdmin-3.1.2.0/scripts/setup.php HTTP/1.0" 404 110
[28/May/2018 16:25:21] "GET /phpMyAdmin-3.4.3.1/scripts/setup.php HTTP/1.0" 404 110
[28/May/2018 16:25:21] "GET /phpMyAdmin2/scripts/setup.php HTTP/1.0" 404 103
[28/May/2018 16:25:22] "GET /phpMyAdmin3/scripts/setup.php HTTP/1.0" 404 103
[28/May/2018 17:04:37] "GET / HTTP/1.0" 200 8061
[28/May/2018 17:25:30] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[28/May/2018 17:35:44] "GET /echo.php?info=1234567890 HTTP/1.0" 400 26
[28/May/2018 17:50:18] "GET /BGCC/Tpl/Public/css/login.css HTTP/1.0" 404 103
[28/May/2018 18:59:39] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[28/May/2018 19:10:58] "GET / HTTP/1.0" 200 8061
[28/May/2018 20:41:53] "GET / HTTP/1.0" 200 8061
[28/May/2018 23:56:08] "GET / HTTP/1.0" 200 8061
[29/May/2018 00:01:02] "GET / HTTP/1.0" 200 8061
[29/May/2018 00:27:10] "GET / HTTP/1.0" 400 26
[29/May/2018 00:29:59] "GET / HTTP/1.0" 200 8061
[29/May/2018 00:30:11] "GET / HTTP/1.0" 200 8061
[29/May/2018 01:23:28] "GET / HTTP/1.0" 200 8061
[29/May/2018 01:32:00] "GET / HTTP/1.0" 200 8061
[29/May/2018 02:19:09] "GET / HTTP/1.0" 200 8061
[29/May/2018 02:19:09] "GET / HTTP/1.0" 200 8061
[29/May/2018 02:30:20] "GET /BGCC/Tpl/Public/css/login.css HTTP/1.0" 404 103
[29/May/2018 02:44:56] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[29/May/2018 03:16:11] "GET / HTTP/1.0" 200 8061
[29/May/2018 03:27:27] "GET / HTTP/1.0" 200 8061
[29/May/2018 03:39:27] "GET /webfig/roteros.info HTTP/1.0" 404 93
[29/May/2018 03:54:08] "GET / HTTP/1.0" 200 8061
[29/May/2018 04:06:18] "GET / HTTP/1.0" 400 26
[29/May/2018 04:17:56] "GET / HTTP/1.0" 200 8061
[29/May/2018 04:58:26] "GET / HTTP/1.0" 200 8061
[29/May/2018 04:59:34] "GET / HTTP/1.0" 200 8061
[29/May/2018 05:10:24] "GET / HTTP/1.0" 200 8061
[29/May/2018 05:34:59] "GET / HTTP/1.0" 200 8061
[29/May/2018 06:00:09] "GET / HTTP/1.0" 200 8061
[29/May/2018 06:10:01] "GET / HTTP/1.0" 200 8061
[29/May/2018 07:26:14] "GET / HTTP/1.0" 200 8061
[29/May/2018 07:52:56] "GET /404/search_children.js HTTP/1.0" 400 26
[29/May/2018 08:32:41] "GET / HTTP/1.0" 400 26
[29/May/2018 09:26:21] "GET / HTTP/1.0" 200 8061
[29/May/2018 09:33:52] "GET / HTTP/1.0" 200 8061
[29/May/2018 09:46:05] "GET / HTTP/1.0" 200 8061
[29/May/2018 10:02:36] "GET / HTTP/1.0" 200 8061
Performing system checks...

System check identified no issues (0 silenced).
May 27, 2018 - 09:18:14
Django version 2.0.5, using settings 'myblog.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[29/May/2018 22:34:02] "GET / HTTP/1.0" 200 8061
[29/May/2018 22:34:02] "GET /favicon.ico HTTP/1.0" 404 85
[29/May/2018 22:34:09] "POST /weixin?signature=61a52d5c1a14c983e22734ae0f3339785f2c8e79&timestamp=1527604449&nonce=556994666&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[29/May/2018 22:37:45] "GET / HTTP/1.0" 200 8061
[29/May/2018 23:31:32] "GET / HTTP/1.0" 200 8061
[29/May/2018 23:31:33] "GET / HTTP/1.0" 200 8061
[29/May/2018 23:31:44] "POST /GponForm/diag_Form?images/ HTTP/1.0" 404 92
[29/May/2018 23:45:43] "GET / HTTP/1.0" 200 8061
[30/May/2018 00:40:28] "GET / HTTP/1.0" 400 26
[30/May/2018 01:00:11] "GET / HTTP/1.0" 200 8061
[30/May/2018 01:17:52] "GET /cgi/common.cgi HTTP/1.0" 404 88
[30/May/2018 01:17:55] "GET /stssys.htm HTTP/1.0" 404 84
[30/May/2018 01:17:58] "GET / HTTP/1.0" 200 8061
[30/May/2018 01:18:03] "POST /command.php HTTP/1.0" 404 85
[30/May/2018 01:24:12] "GET / HTTP/1.0" 200 8061
[30/May/2018 01:36:14] "GET / HTTP/1.0" 200 8061
[30/May/2018 01:36:20] "GET / HTTP/1.0" 200 8061
[30/May/2018 01:44:54] "GET / HTTP/1.0" 200 8061
[30/May/2018 01:46:51] "GET / HTTP/1.0" 200 8061
[30/May/2018 02:12:14] "GET /currentsetting.htm HTTP/1.0" 404 92
[30/May/2018 02:23:32] "GET / HTTP/1.0" 200 8061
[30/May/2018 02:47:09] "GET / HTTP/1.0" 400 26
[30/May/2018 03:14:25] "GET / HTTP/1.0" 400 26
[30/May/2018 03:20:34] "GET / HTTP/1.0" 200 8061
[30/May/2018 03:32:05] "GET / HTTP/1.0" 200 8061
[30/May/2018 03:51:44] "GET / HTTP/1.0" 200 8061
[30/May/2018 04:28:11] "GET / HTTP/1.0" 200 8061
[30/May/2018 05:33:20] "GET / HTTP/1.0" 200 8061
[30/May/2018 05:40:35] "GET / HTTP/1.0" 400 26
[30/May/2018 06:49:27] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[30/May/2018 07:07:56] "GET / HTTP/1.0" 200 8061
[30/May/2018 07:42:36] "GET /echo.php HTTP/1.0" 400 26
[30/May/2018 07:53:12] "POST /weixin?signature=7f190147df5213ca68c07fe53784dbbca0f067cc&timestamp=1527637992&nonce=955461260&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 500 27
[30/May/2018 07:53:17] "POST /weixin?signature=d71685fabbff835b14693b5f2cfa870bcbd3ea57&timestamp=1527637997&nonce=1700861898&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 500 27
[30/May/2018 07:53:20] "POST /weixin?signature=fcfac2df55058b5c32ccbafb124a8f3c3d8126db&timestamp=1527638000&nonce=1825467877&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 200 318
[30/May/2018 07:53:23] "POST /weixin?signature=f1f8188ad2ce7bf73a66a5ab9a1ba721c8579df1&timestamp=1527638003&nonce=1478113209&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 500 27
[30/May/2018 07:53:26] "POST /weixin?signature=9959139ba3c64e8f4d1badc049651e4ea5e1d79a&timestamp=1527638006&nonce=1023598421&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 500 27
[30/May/2018 07:54:28] "POST /weixin?signature=0dd4d31807f2fc7653c1af1aa4ad4bf0cef3e561&timestamp=1527638061&nonce=2028402262&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 07:54:33] "POST /weixin?signature=0dd4d31807f2fc7653c1af1aa4ad4bf0cef3e561&timestamp=1527638061&nonce=2028402262&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 07:54:37] "POST /weixin?signature=0dd4d31807f2fc7653c1af1aa4ad4bf0cef3e561&timestamp=1527638061&nonce=2028402262&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 07:54:55] "POST /weixin?signature=6f8000ff5b858a4d7ddfc87312b4219a523066bd&timestamp=1527638095&nonce=922464922&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 311
[30/May/2018 07:55:07] "POST /weixin?signature=eac83fff1bb8da05d6a322313b71b97e26008413&timestamp=1527638107&nonce=329496091&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 313
[30/May/2018 08:28:06] "GET / HTTP/1.0" 200 8061
[30/May/2018 08:49:18] "GET / HTTP/1.0" 400 26
[30/May/2018 09:13:00] "GET / HTTP/1.0" 200 8061
[30/May/2018 09:20:54] "GET / HTTP/1.0" 200 8061
[30/May/2018 17:31:00] "POST /weixin?signature=231cb8c47990aa528f52095dc4120b224b03d9c0&timestamp=1527672652&nonce=547759898&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 17:31:08] "POST /weixin?signature=231cb8c47990aa528f52095dc4120b224b03d9c0&timestamp=1527672652&nonce=547759898&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 17:31:10] "POST /weixin?signature=231cb8c47990aa528f52095dc4120b224b03d9c0&timestamp=1527672652&nonce=547759898&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 17:31:42] "POST /weixin?signature=7a54ece6ad197052700044c2fbf953a80af92e21&timestamp=1527672702&nonce=1241370050&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 17:31:57] "POST /weixin?signature=db09c5f0f003db72db1d4785667603a150dd02e0&timestamp=1527672707&nonce=841922191&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 500 27
[30/May/2018 17:32:01] "POST /weixin?signature=db09c5f0f003db72db1d4785667603a150dd02e0&timestamp=1527672707&nonce=841922191&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 17:41:57] "POST /weixin?signature=b4512f82ecf44aa4caeffbae7f577807704b6ca7&timestamp=1527673317&nonce=341404761&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 313
[30/May/2018 17:42:04] "POST /weixin?signature=596601ce35670ada8647a7b18d6edb2325955254&timestamp=1527673324&nonce=2142911676&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 310
[30/May/2018 17:42:09] "POST /weixin?signature=ce9c4915fc75739eb21cf64395c2fcec771dfed9&timestamp=1527673329&nonce=2127174783&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 311
[30/May/2018 17:42:12] "POST /weixin?signature=6de77f7c3f5cae9566626fd42dc0ce7dcfb73c77&timestamp=1527673332&nonce=1695550908&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 294
[30/May/2018 18:05:51] "GET /echo.php?info=1234567890 HTTP/1.0" 400 26
[30/May/2018 19:18:35] "GET / HTTP/1.0" 200 8061
[30/May/2018 19:36:29] "GET / HTTP/1.0" 200 8061
[30/May/2018 21:43:55] "POST /weixin?signature=d2766919566e6fb4f320c51bb5785271b4cb2401&timestamp=1527687835&nonce=853696622&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 294
[30/May/2018 21:44:03] "POST /weixin?signature=1fee5d07348af1561f9964e35fdeb78b047b2966&timestamp=1527687843&nonce=1391225507&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[30/May/2018 21:45:06] "POST /weixin?signature=fe6c4e61515ae0aede4ec7821aea461706812208&timestamp=1527687906&nonce=1319094329&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 294
[30/May/2018 21:45:40] "POST /weixin?signature=ef7118775071f60a7ca79c85a3d49b0e5449235a&timestamp=1527687940&nonce=833948327&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 438
[30/May/2018 21:46:47] "GET / HTTP/1.0" 200 8061
[30/May/2018 22:02:22] "GET / HTTP/1.0" 200 8061
[30/May/2018 22:38:50] "GET / HTTP/1.0" 200 8061
[31/May/2018 00:10:19] "GET / HTTP/1.0" 200 8061
[31/May/2018 00:10:52] "GET / HTTP/1.0" 200 8061
[31/May/2018 00:24:30] "GET / HTTP/1.0" 400 26
[31/May/2018 00:30:35] "GET / HTTP/1.0" 200 8061
[31/May/2018 01:07:45] "GET / HTTP/1.0" 200 8061
[31/May/2018 01:25:46] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[31/May/2018 02:37:46] "GET / HTTP/1.0" 200 8061
[31/May/2018 03:15:22] "GET / HTTP/1.0" 200 8061
[31/May/2018 03:35:44] "GET / HTTP/1.0" 400 26
[31/May/2018 03:36:56] "GET / HTTP/1.0" 200 8061
[31/May/2018 03:44:09] "GET / HTTP/1.0" 200 8061
[31/May/2018 03:46:27] "GET / HTTP/1.0" 200 8061
[31/May/2018 04:46:33] "GET / HTTP/1.0" 200 8061
[31/May/2018 04:59:07] "GET / HTTP/1.0" 200 8061
[31/May/2018 05:17:34] "GET / HTTP/1.0" 200 8061
[31/May/2018 06:49:29] "GET / HTTP/1.0" 200 8061
[31/May/2018 07:17:05] "POST /weixin?signature=f452c782df107966587037eb425a6bfe57144914&timestamp=1527722225&nonce=1915990395&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 294
[31/May/2018 07:17:30] "POST /weixin?signature=1f61a28d5ba6a9b8159f11b6eefce096fefaeb8c&timestamp=1527722240&nonce=345448886&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 500 27
[31/May/2018 07:17:37] "POST /weixin?signature=1f61a28d5ba6a9b8159f11b6eefce096fefaeb8c&timestamp=1527722240&nonce=345448886&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[31/May/2018 07:17:44] "POST /weixin?signature=359472b16415425aa56d7fc976e180251386df1c&timestamp=1527722264&nonce=1110243325&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 318
[31/May/2018 07:17:49] "POST /weixin?signature=03e5c69fd2092a0675e1ec2cf10884602a6d490e&timestamp=1527722269&nonce=270984412&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 314
[31/May/2018 07:17:58] "POST /weixin?signature=606030f0908aae57df882beeeb3717329643c3ce&timestamp=1527722278&nonce=1547405268&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 316
[31/May/2018 08:06:14] "GET / HTTP/1.0" 200 8061
[31/May/2018 08:14:25] "GET / HTTP/1.0" 200 8061
[31/May/2018 08:20:30] "GET / HTTP/1.0" 400 26
[31/May/2018 08:21:32] "GET / HTTP/1.0" 200 8061
[31/May/2018 08:43:09] "GET / HTTP/1.0" 200 8061
[31/May/2018 09:34:39] "GET /w00tw00t.at.blackhats.romanian.anti-sec:) HTTP/1.0" 404 115
[31/May/2018 09:34:39] "GET /phpMyAdmin/scripts/setup.php HTTP/1.0" 404 102
[31/May/2018 09:34:39] "GET /phpmyadmin/scripts/setup.php HTTP/1.0" 404 102
[31/May/2018 09:34:40] "GET /pma/scripts/setup.php HTTP/1.0" 404 95
[31/May/2018 09:34:40] "GET /myadmin/scripts/setup.php HTTP/1.0" 404 99
[31/May/2018 09:34:40] "GET /MyAdmin/scripts/setup.php HTTP/1.0" 404 99
[31/May/2018 17:33:07] "POST /weixin?signature=f4d54ae3f9a59c263175ed37c9694d2a26b67db4&timestamp=1527759187&nonce=185596294&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 438
[31/May/2018 17:41:58] "POST /weixin?signature=d1ef4671be5247650e8093837a05830f86cc6d10&timestamp=1527759718&nonce=1742177885&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 316
[31/May/2018 17:42:07] "POST /weixin?signature=de10ef7450e6316636b21e1b00a4b4014c09caf5&timestamp=1527759727&nonce=538353560&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 317
[31/May/2018 17:42:17] "POST /weixin?signature=a750e277e0207c87f6c60fedfd4de161cfaa790a&timestamp=1527759737&nonce=1428952875&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 294
[31/May/2018 17:42:19] "GET / HTTP/1.0" 200 8061
[31/May/2018 17:42:19] "GET / HTTP/1.0" 200 8061
[31/May/2018 18:07:44] "GET / HTTP/1.0" 200 8061
Performing system checks...

System check identified no issues (0 silenced).
May 31, 2018 - 17:32:51
Django version 2.0.5, using settings 'myblog.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
(1,)
[31/May/2018 22:38:59] "GET / HTTP/1.0" 200 8061
[31/May/2018 22:45:11] "POST /weixin?signature=f2a730eefd46e0c8b0b412df0626e52b9c3c4d67&timestamp=1527777911&nonce=270153974&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 200 317
[31/May/2018 22:45:15] "POST /weixin?signature=8576d6faee145221a83f264c07fd4aa7be7892c1&timestamp=1527777915&nonce=668445989&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 200 314
[31/May/2018 22:45:17] "POST /weixin?signature=7e8f3dab385ed5499a4e888637100eeb1249cc29&timestamp=1527777917&nonce=1050555407&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 200 317
[31/May/2018 22:45:21] "POST /weixin?signature=ac180ccd743a890e954cf6161bd5fc2d44548c28&timestamp=1527777921&nonce=1448610473&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 200 294
[31/May/2018 22:45:30] "POST /weixin?signature=691664e63883bf31913384dc49cba1612c3300fa&timestamp=1527777930&nonce=1978700360&openid=oQZgM1FLG1J5B6u1YmzCCKPfjnng HTTP/1.0" 200 294
[31/May/2018 22:49:03] "POST /weixin?signature=c8266ed0b69fe1372fc47a6fc383ef347d1e750f&timestamp=1527778143&nonce=199314677&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 647
[31/May/2018 22:49:24] "POST /weixin?signature=66f2e5b972494c40974106c7900dfbcc3274cbe1&timestamp=1527778164&nonce=79957132&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 316
[31/May/2018 22:49:39] "POST /weixin?signature=1a273c5702ca5a703d4351068da978bf5ce75e3d&timestamp=1527778179&nonce=345628789&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 318
[31/May/2018 22:54:45] "POST /weixin?signature=94314dac20593939fa44129fc988024adcddc0e1&timestamp=1527778485&nonce=1225130686&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 317
[31/May/2018 22:54:59] "POST /weixin?signature=1deb42cdb08ef2d28b5cb4e46200c21a66ed6374&timestamp=1527778499&nonce=1338133653&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 317
[31/May/2018 23:05:04] "POST /weixin?signature=1cd4d56d3ddf4bd1d0ad0f8f3380ec2747607451&timestamp=1527779104&nonce=76724319&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 313
[31/May/2018 23:39:39] "GET / HTTP/1.0" 200 8061
[31/May/2018 23:39:39] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 00:14:54] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 00:15:30] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 00:26:26] "GET / HTTP/1.0" 400 26
[01/Jun/2018 01:36:18] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 02:43:05] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 02:43:12] "GET /robots.txt HTTP/1.0" 404 84
[01/Jun/2018 02:43:17] "GET /.well-known/security.txt HTTP/1.0" 404 98
[01/Jun/2018 02:43:30] "GET /favicon.ico HTTP/1.0" 404 85
[01/Jun/2018 02:56:18] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 04:06:05] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 04:12:53] "GET / HTTP/1.0" 400 26
[01/Jun/2018 04:14:20] "GET / HTTP/1.0" 200 8061
[01/Jun/2018 04:52:16] "POST /weixin?signature=b809fd550b77cec7cde79bae0d5ef5b4046ed9af&timestamp=1527799936&nonce=1793350336&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 294
[01/Jun/2018 04:53:20] "POST /weixin?signature=1cd4c8989ca4b420b221eac397c75212e22f3ff1&timestamp=1527799999&nonce=1634627736&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[01/Jun/2018 04:53:38] "POST /weixin?signature=ca801265d4fce24201fdebadbf31d0a6b261da19&timestamp=1527800013&nonce=1845715749&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 316
[01/Jun/2018 04:53:44] "POST /weixin?signature=ca801265d4fce24201fdebadbf31d0a6b261da19&timestamp=1527800013&nonce=1845715749&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 285
[01/Jun/2018 04:53:48] "POST /weixin?signature=1a63e85b9bf256bb7afcc06a7f3d1fe41f446660&timestamp=1527800028&nonce=2127523658&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 298
[01/Jun/2018 04:53:56] "GET /cache/global/img/gs.gif HTTP/1.0" 400 26
[01/Jun/2018 04:54:09] "POST /weixin?signature=d22b14e53791246e0c07f90218d28eba0348038f&timestamp=1527800049&nonce=801846517&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 298
[01/Jun/2018 04:54:32] "POST /weixin?signature=b1057ae41c86089a888800f118a2f4fb7d8e37b7&timestamp=1527800072&nonce=747236292&openid=oQZgM1FtJ-VydGM9QUWw-Lkjv9CM HTTP/1.0" 200 2593
